create table ll_livestack_event_users (
    id                 number generated by default on null as identity,
    livestack_event_id number not null,
    owner1             varchar2(50),
    date_entered       date,
    constraint ll_livestack_event_users_pk primary key (id),
    constraint ll_lse_users_event_fk foreign key (livestack_event_id)
        references ll_livestack_events (id) on delete cascade
);

create or replace editionable trigger ll_livestack_event_users_bi_trg
    before insert on ll_livestack_event_users
    for each row
begin
    :new.owner1 := upper(:new.owner1);
end;
/
alter trigger ll_livestack_event_users_bi_trg enable;

create index ll_lse_users_event_idx on ll_livestack_event_users (livestack_event_id);
create index ll_lse_users_owner_idx on ll_livestack_event_users (owner1);

comment on table ll_livestack_event_users is
    'Tracks users who have entered a LiveStack parent event code.';
comment on column ll_livestack_event_users.id is
    'ID of the entry.';
comment on column ll_livestack_event_users.livestack_event_id is
    'ID of the LiveStack event used.';
comment on column ll_livestack_event_users.owner1 is
    'Username of the person using the LiveStack event code.';
comment on column ll_livestack_event_users.date_entered is
    'Date/time the LiveStack event code was entered.';
