create table ll_livestack_events (
    id              number generated by default on null as identity,
    event_code      varchar2(50),
    livestack_id    number not null,
    active_flg      varchar2(1) default 'Y',
    email_creator   varchar2(200),
    email_requestor varchar2(4000),
    valid_from      date,
    valid_to        date,
    valid_timezone  varchar2(50),
    remarks         varchar2(4000),
    constraint ll_livestack_events_pk primary key (id),
    constraint ll_livestack_events_uk unique (event_code),
    constraint ll_livestack_events_active_ck check (active_flg in ('N','Y')),
    constraint ll_livestack_events_ls_fk foreign key (livestack_id)
        references ll_livestacks (id)
);

create table ll_livestack_event_vouchers (
    id                  number generated by default on null as identity,
    livestack_event_id  number not null,
    livestack_entry_id  number not null,
    voucher_id          number not null,
    active_flg          varchar2(1) default 'Y',
    constraint ll_livestack_event_vouchers_pk primary key (id),
    constraint ll_lse_vouchers_active_ck check (active_flg in ('N','Y')),
    constraint ll_lse_vouchers_event_fk foreign key (livestack_event_id)
        references ll_livestack_events (id) on delete cascade,
    constraint ll_lse_vouchers_entry_fk foreign key (livestack_entry_id)
        references ll_livestack_entries (id) on delete cascade,
    constraint ll_lse_vouchers_voucher_fk foreign key (voucher_id)
        references ll_vouchers (id),
    constraint ll_lse_vouchers_entry_uk unique (livestack_event_id, livestack_entry_id)
);

create or replace editionable trigger ll_livestack_events_trg
    before insert on ll_livestack_events
    for each row
begin
    if :new.event_code is null then
        :new.event_code := replace(
            to_char(:new.id, '00000') || '-' ||
            replace(
                dbms_random.string(opt => 'U', len => 4) || '-' || dbms_random.string(opt => 'U', len => 4),
                'O',
                'X'
            ),
            ' ',
            ''
        );
    end if;
end;
/
alter trigger ll_livestack_events_trg enable;

create index ll_lse_livestack_idx on ll_livestack_events (livestack_id);
create index ll_lse_active_dates_idx on ll_livestack_events (active_flg, valid_from, valid_to);
create index ll_lse_vouchers_voucher_idx on ll_livestack_event_vouchers (voucher_id);

comment on table ll_livestack_events is
    'LiveStack parent event code. Child entry event codes remain existing LL_VOUCHERS records.';
comment on table ll_livestack_event_vouchers is
    'Maps a LiveStack event entry to an existing LL_VOUCHERS event code.';
comment on column ll_livestack_events.event_code is
    'Public LiveStack event code generated with the same format as LL_VOUCHERS.VOUCHER_CODE.';
