alter table wms_livestack_events add constraint wms_livestack_events_id_ls_uk
    unique (id, livestack_id);

alter table wms_livestack_entries add constraint wms_ls_entries_id_ls_uk
    unique (id, livestack_id);

alter table wms_events add (
    livestack_event_id number
);

alter table wms_events add constraint wms_events_lse_fk
    foreign key (livestack_event_id)
    references wms_livestack_events (id)
    on delete set null;

create index wms_events_lse_idx on wms_events (livestack_event_id);

create table wms_livestack_event_entries (
    id                  number generated by default on null as identity,
    livestack_event_id  number not null,
    livestack_id        number not null,
    livestack_entry_id  number not null,
    event_id            number not null,
    active_flg          varchar2(1) default 'Y' not null,
    created_date        date default sysdate not null,
    created_by          varchar2(300),
    updated_on          date,
    updated_by          varchar2(300),
    constraint wms_lse_entries_pk primary key (id),
    constraint wms_lse_entries_event_fk foreign key (livestack_event_id, livestack_id)
        references wms_livestack_events (id, livestack_id)
        on delete cascade,
    constraint wms_lse_entries_entry_fk foreign key (livestack_entry_id, livestack_id)
        references wms_livestack_entries (id, livestack_id)
        on delete cascade,
    constraint wms_lse_entries_wms_event_fk foreign key (event_id)
        references wms_events (id)
        on delete cascade,
    constraint wms_lse_entries_entry_uk unique (livestack_event_id, livestack_entry_id)
);

create index wms_lse_entries_ls_idx on wms_livestack_event_entries (livestack_id);
create index wms_lse_entries_entry_idx on wms_livestack_event_entries (livestack_entry_id);
create index wms_lse_entries_event_idx on wms_livestack_event_entries (event_id);

comment on table wms_livestack_event_entries is
    'Maps each LiveStack event entry to the WMS_EVENTS request created for that entry.';
comment on column wms_livestack_event_entries.event_id is
    'WMS_EVENTS.ID for the event request associated with this LiveStack entry.';
comment on column wms_events.livestack_event_id is
    'Parent WMS_LIVESTACK_EVENTS.ID when this event was generated for a LiveStack event entry.';
