create table wms_livestack_events (
    id                     number generated by default on null as identity,
    livestack_id           number not null,
    event_code             varchar2(50),
    event_title            varchar2(1000),
    email_creator          varchar2(200),
    email_requestor        varchar2(4000),
    valid_from             date,
    valid_to               date,
    valid_timezone         varchar2(50),
    active_flg             varchar2(1) default 'Y' not null,
    desc_long_override     varchar2(4000),
    outline_override       varchar2(4000),
    prereqs_override       varchar2(4000),
    remarks                varchar2(4000),
    event_status           varchar2(50) default 'Submitted' not null,
    updated_flg            number default 0 not null,
    created_date           date default sysdate not null,
    created_by             varchar2(300),
    updated_on             date,
    updated_by             varchar2(300),
    constraint wms_livestack_events_pk primary key (id),
    constraint wms_lse_livestack_fk foreign key (livestack_id)
        references wms_livestacks (id)
        on delete cascade
);


create table wms_livestack_event_entries (
    id                  number generated by default on null as identity,
    livestack_event_id  number not null,
    livestack_id        number not null,
    livestack_entry_id  number not null,
    event_id            number not null,
    active_flg          varchar2(1) default 'Y' not null,
    created_date        date default sysdate not null,
    created_by          varchar2(300),
    updated_on          date,
    updated_by          varchar2(300),
    constraint wms_lse_entries_pk primary key (id),
    constraint wms_lse_entries_event_fk foreign key (livestack_event_id, livestack_id)
        references wms_livestack_events (id, livestack_id)
        on delete cascade,
    constraint wms_lse_entries_entry_fk foreign key (livestack_entry_id, livestack_id)
        references wms_livestack_entries (id, livestack_id)
        on delete cascade,
    constraint wms_lse_entries_wms_event_fk foreign key (event_id)
        references wms_events (id)
        on delete cascade,
    constraint wms_lse_entries_entry_uk unique (livestack_event_id, livestack_entry_id)
);

create index wms_lse_livestack_idx on wms_livestack_events (livestack_id);
create index wms_lse_status_idx on wms_livestack_events (event_status, updated_flg);
create index wms_lse_entries_ls_idx on wms_livestack_event_entries (livestack_id);
create index wms_lse_entries_entry_idx on wms_livestack_event_entries (livestack_entry_id);
create index wms_lse_entries_event_idx on wms_livestack_event_entries (event_id);

comment on table wms_livestack_events is
    'WMS request record for a LiveStack event. Entry-level workshop events are stored in WMS_EVENTS and linked through WMS_LIVESTACK_EVENT_ENTRIES.';
comment on table wms_livestack_event_entries is
    'Maps each LiveStack event entry to the WMS_EVENTS request created for that entry.';
comment on column wms_livestack_events.id is
    'WMS LiveStack event request ID. Generated by identity, but may be supplied explicitly when needed.';
comment on column wms_livestack_events.event_code is
    'LiveLabs LiveStack event code populated after the event is published/synced.';
comment on column wms_livestack_events.event_title is
    'Display title for the LiveStack event.';
comment on column wms_livestack_events.event_status is
    'WMS approval/publication status for the LiveStack event request.';
comment on column wms_livestack_event_entries.event_id is
    'WMS_EVENTS.ID for the event request associated with this LiveStack entry.';
