-- HTTPS endpoint pool schema.
--
-- Run once, before 002_ll_pkg_reserved_public_ips.sql and the package/APEX
-- deployment. This is a forward-only migration; it intentionally contains no
-- destructive statements.

ALTER TABLE ll_tf_scripts ADD (
  https_enabled_flg VARCHAR2(1) DEFAULT 'N' NOT NULL
);

ALTER TABLE ll_tf_scripts ADD CONSTRAINT ll_tf_scripts_ck_https
  CHECK (https_enabled_flg IN ('Y', 'N'));

CREATE TABLE ll_reserved_public_ips (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name             VARCHAR2(200) NOT NULL,
  ip_address       VARCHAR2(45) NOT NULL,
  ip_ocid          VARCHAR2(4000) NOT NULL,
  tenancy_id       NUMBER NOT NULL,
  region_id        NUMBER NOT NULL,
  dns_entry        VARCHAR2(255) NOT NULL,
  cert_common_name VARCHAR2(255),
  cert_ocid        VARCHAR2(4000),
  ca_bundle_ocid   VARCHAR2(4000),
  active_flg       VARCHAR2(1) DEFAULT 'N' NOT NULL,
  reservation_id   NUMBER,
  last_used_on     TIMESTAMP(6) WITH TIME ZONE,
  allocated_on     TIMESTAMP(6) WITH TIME ZONE,
  released_on      TIMESTAMP(6) WITH TIME ZONE,
  last_oci_check_on TIMESTAMP(6) WITH TIME ZONE,
  last_oci_lifecycle_state VARCHAR2(30),
  last_oci_assigned_entity_id VARCHAR2(4000),
  CONSTRAINT ll_rpip_pk PRIMARY KEY (id),
  CONSTRAINT ll_rpip_uk_ip_ocid UNIQUE (ip_ocid),
  CONSTRAINT ll_rpip_uk_reservation UNIQUE (reservation_id),
  CONSTRAINT ll_rpip_fk_tenancy FOREIGN KEY (tenancy_id)
    REFERENCES ll_tenancies (id),
  CONSTRAINT ll_rpip_fk_region FOREIGN KEY (region_id)
    REFERENCES ll_oci_regions (id),
  CONSTRAINT ll_rpip_fk_reservation FOREIGN KEY (reservation_id)
    REFERENCES ll_reservations (id),
  CONSTRAINT ll_rpip_ck_active CHECK (active_flg IN ('Y', 'N')),
  CONSTRAINT ll_rpip_ck_tls_config CHECK (
    active_flg = 'N'
    OR (cert_ocid IS NOT NULL AND ca_bundle_ocid IS NOT NULL)
  )
);

CREATE INDEX ll_rpip_ix_allocate
  ON ll_reserved_public_ips (
    tenancy_id,
    region_id,
    active_flg,
    reservation_id,
    last_used_on,
    id
  );
